### PR TITLE
Fix cargo deny

### PR DESCRIPTION
**Pull request by AldaronLau**
WIP stuff I forgot to push before for enabling security checks with cargo deny

### CODE REVIEW

**Comment by CATboardBETA** [comment]
@AldaronLau Is this still needed?

**Comment by AldaronLau** [comment]
Yeah, this will still be required.  The `cargo deny` checking doesn't fully work yet; there's a couple more things to do.

**Review by CATboardBETA — APPROVED** [review]
Looks good to me! Only thing I might add is in the list of allowed licenses is like MIT and stuff

**Comment by AldaronLau** [comment]
> Looks good to me! Only thing I might add is in the list of allowed licenses is like MIT and stuff

It's actually already in there :slightly_smiling_face:.  We can add more as we need them

https://github.com/ardaku/quantii/blob/056d6d8947ba5974c51563c28583239c24abfdab/deny.toml#L82

**Pull request merged**
